quarkus:
  http:
    port: 8080
    root-path: /api
    non-application-root-path: /q

  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    jdbc:
      url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:main-service-db}

  hibernate-orm:
    database:
        generation: validate
    mapping:
      format:
        global: ignore

  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml

  container-image:
    builder: jib
    build: false
    group: "artem5252"
    name: "quingo-main-service"
    tag: "latest"
