apiVersion: v1
kind: Service
metadata:
  name: main-postgres-service
  namespace: quingo-app
spec:
  selector:
    app: main-postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None