apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  namespace: quingo-app
  labels:
    app: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service-container
          image: artem5252/quingo-main-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: main-service-secret
                  key: REDIS_PORT

          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"

          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
