apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  namespace: quingo-app
  labels:
    app: main-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-service-container
          image: artem5252/quingo-main-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
